baseURL = '/'
languageCode = 'en-us'
title = 'Learnado'
theme = 'hugo-theme-learn'

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  showVisitedLinks = true
