# .goreleaser.yml
archives:
- files:
  - hugo/
  - frontend/build/
  - homepage.md
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
